cmd_/home/os/116_CSIE/Operating_Systems/HW1/some_function.o := gcc -Wp,-MD,/home/os/116_CSIE/Operating_Systems/HW1/.some_function.o.d  -nostdinc -isystem /usr/lib/gcc/i686-linux-gnu/5/include  -I./arch/x86/include -Iarch/x86/include/generated/uapi -Iarch/x86/include/generated  -Iinclude -I./arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -Iubuntu/include  -D__KERNEL__ -fno-pie -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-pie -no-pie -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m32 -msoft-float -mregparm=3 -freg-struct-return -fno-pic -mpreferred-stack-boundary=2 -march=i686 -mtune=generic -maccumulate-outgoing-args -Wa,-mtune=generic32 -ffreestanding -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DCC_HAVE_ASM_GOTO  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(some_function)"  -D"KBUILD_MODNAME=KBUILD_STR(hw1)" -c -o /home/os/116_CSIE/Operating_Systems/HW1/.tmp_some_function.o /home/os/116_CSIE/Operating_Systems/HW1/some_function.c

source_/home/os/116_CSIE/Operating_Systems/HW1/some_function.o := /home/os/116_CSIE/Operating_Systems/HW1/some_function.c

deps_/home/os/116_CSIE/Operating_Systems/HW1/some_function.o := \
  /home/os/116_CSIE/Operating_Systems/HW1/some_function.h \

/home/os/116_CSIE/Operating_Systems/HW1/some_function.o: $(deps_/home/os/116_CSIE/Operating_Systems/HW1/some_function.o)

$(deps_/home/os/116_CSIE/Operating_Systems/HW1/some_function.o):
